export const exchangeConstants = {
  GET_EXCHANGE_RATE_REQUEST: 'GET_EXCHANGE_RATE_REQUEST',
  GET_EXCHANGE_RATE_SUCCESS: 'GET_EXCHANGE_RATE_SUCCESS',
  GET_EXCHANGE_RATE_FAILURE: 'GET_EXCHANGE_RATE_FAILURE'
};